package de.cloudnetwork.proxygw;

import de.cloudnetwork.config.CloudConfig;
import de.cloudnetwork.config.ConfigManager;
import de.cloudnetwork.console.ConsoleOutput;
import de.cloudnetwork.database.MongoDbDatabaseManager;
import de.cloudnetwork.protocol.ProxyEndpoint;
import de.cloudnetwork.tls.TlsManager;
import de.cloudnetwork.worker.WorkerInfo;
import org.bson.Document;

import javax.net.ssl.SSLContext;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * Entry point for the <b>CloudNetwork ProxyGateway</b>.
 *
 * <p>The ProxyGateway acts as the single public entry-point for Minecraft
 * clients.  It maintains a list of available Velocity proxy servers, obtained
 * from:
 * <ol>
 *   <li>Direct DB query on startup and every 60 seconds as a fallback.</li>
 *   <li>Live {@code PROXY_UPDATE} pushes from the Main Gateway via the
 *       persistent socket connection.</li>
 * </ol>
 * Incoming Minecraft connections are forwarded to one of the proxies using
 * round-robin load balancing via a transparent TCP relay.</p>
 *
 * <p>Configuration is read from the database (keys below) or from environment
 * variables as a fallback:</p>
 * <table border="1">
 *   <tr><th>DB key</th><th>Env var</th><th>Default</th></tr>
 *   <tr><td>proxy_gateway_id</td><td>PROXY_GATEWAY_ID</td><td>proxy-gateway-01</td></tr>
 *   <tr><td>proxy_gateway_auth_token</td><td>PROXY_GATEWAY_AUTH_TOKEN</td><td>–</td></tr>
 *   <tr><td>proxy_gateway_port</td><td>PROXY_GATEWAY_PORT</td><td>25565</td></tr>
 *   <tr><td>gateway_host</td><td>GATEWAY_HOST</td><td>–</td></tr>
 *   <tr><td>gateway_port</td><td>GATEWAY_PORT</td><td>9876</td></tr>
 * </table>
 */
public class ProxyGatewayMain {

    public static void main(String[] args) {
        printBanner();

        MongoDbDatabaseManager db = new MongoDbDatabaseManager();
        ProxyGatewayServer proxyServer = null;
        ProxyGatewayClient gatewayClient = null;
        ScheduledExecutorService scheduler = null;
        AtomicBoolean running = new AtomicBoolean(true);

        try {
            // ── 1. Load config & connect to DB ────────────────────────────────
            CloudConfig config = ConfigManager.load();
            db.connect(config.getDbHost(), config.getDbPort(), config.getDbName(),
                    config.getDbUser(), config.getDbPassword());
            ConsoleOutput.info("[OK] Datenbankverbindung hergestellt.");

            // ── 2. Read configuration ─────────────────────────────────────────
            String gatewayId = readValue(db, "proxy_gateway_id", "PROXY_GATEWAY_ID");
            if (gatewayId == null || gatewayId.isBlank()) gatewayId = "proxy-gateway-01";

            String authToken = readValue(db, "proxy_gateway_auth_token", "PROXY_GATEWAY_AUTH_TOKEN");
            if (authToken == null || authToken.isBlank()) {
                throw new IllegalStateException(
                        "proxy_gateway_auth_token fehlt in der DB. Führe den Setup-Wizard erneut aus.");
            }

            String gatewayHost = readValue(db, "gateway_host", "GATEWAY_HOST");
            if (gatewayHost == null || gatewayHost.isBlank()) {
                throw new IllegalStateException("gateway_host fehlt in der DB.");
            }
            int gatewayPort = readIntValue(db, "gateway_port", "GATEWAY_PORT", 9876);
            int proxyPort = readIntValue(db, "proxy_gateway_port", "PROXY_GATEWAY_PORT", 25565);

            ConsoleOutput.info("[INFO] Gateway: " + gatewayHost + ":" + gatewayPort);
            ConsoleOutput.info("[INFO] Proxy-Port: " + proxyPort);

            // Load mTLS client context (certs generated by the Master Gateway).
            SSLContext sslContext = TlsManager.createClientSSLContext(db);

            // ── 3. Start ProxyGatewayServer ───────────────────────────────────
            proxyServer = new ProxyGatewayServer(proxyPort);

            // Pre-load proxy list from DB so we can accept connections even before
            // the socket connection to the Main Gateway is established.
            proxyServer.updateProxyList(loadProxyListFromDb(db));

            proxyServer.start();

            // ── 4. Start ProxyGatewayClient (socket to Main Gateway) ──────────
            final ProxyGatewayServer finalProxyServer = proxyServer;
            gatewayClient = new ProxyGatewayClient(gatewayHost, gatewayPort, gatewayId, authToken,
                    finalProxyServer, sslContext);
            Thread clientThread = new Thread(gatewayClient, "proxy-gateway-client");
            clientThread.setDaemon(true);
            clientThread.start();

            // ── 5. Periodic DB refresh as fallback ────────────────────────────
            final ProxyGatewayServer serverRef = proxyServer;
            scheduler = Executors.newSingleThreadScheduledExecutor(
                    r -> new Thread(r, "proxy-gateway-db-refresh"));
            scheduler.scheduleAtFixedRate(() -> {
                try {
                    List<ProxyEndpoint> proxies = loadProxyListFromDb(db);
                    serverRef.updateProxyList(proxies);
                    ConsoleOutput.logOnly("[INFO] Proxy-Liste aus DB aktualisiert: " + proxies.size() + " Proxy(s)");
                } catch (Exception e) {
                    ConsoleOutput.error("[FEHLER] DB-Refresh fehlgeschlagen: " + e.getMessage());
                }
            }, 60, 60, TimeUnit.SECONDS);

            ConsoleOutput.info("");
            ConsoleOutput.info("[OK] ProxyGateway ist bereit. Tippe 'stop' zum Beenden.");

            // ── 6. Console loop ───────────────────────────────────────────────
            try (Scanner scanner = new Scanner(System.in)) {
                while (running.get() && scanner.hasNextLine()) {
                    String line = scanner.nextLine().trim();
                    if ("stop".equalsIgnoreCase(line)) break;
                    if ("list".equalsIgnoreCase(line)) {
                        List<ProxyEndpoint> current = serverRef.getProxyList();
                        ConsoleOutput.info("Aktive Proxys (" + current.size() + "):");
                        for (ProxyEndpoint ep : current) {
                            ConsoleOutput.info("  " + ep.instanceId() + " → " + ep.host() + ":" + ep.port());
                        }
                    }
                }
            }

        } catch (Exception e) {
            ConsoleOutput.error("[FEHLER] ProxyGateway konnte nicht gestartet werden: " + e.getMessage());
            ConsoleOutput.logException(e);
            System.exit(1);
        } finally {
            running.set(false);
            if (scheduler != null) scheduler.shutdownNow();
            if (gatewayClient != null) gatewayClient.stop();
            if (proxyServer != null) proxyServer.stop();
            db.close();
        }
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /**
     * Queries the DB for ONLINE VELOCITY instances and resolves each one to its
     * worker's public IPv4 address, building a list of {@link ProxyEndpoint}s.
     */
    static List<ProxyEndpoint> loadProxyListFromDb(MongoDbDatabaseManager db) {
        List<ProxyEndpoint> proxies = new ArrayList<>();
        try {
            for (Document inst : db.getOnlineVelocityInstances()) {
                String instanceId = inst.getString("_id");
                Object portObj = inst.get("port");
                int port = portObj instanceof Number n ? n.intValue() : 25565;
                String workerId = readWorkerId(inst);
                if (workerId == null) continue;
                WorkerInfo worker = db.getWorker(workerId);
                if (worker != null && worker.getIpv4() != null && !worker.getIpv4().isBlank()) {
                    proxies.add(new ProxyEndpoint(instanceId, worker.getIpv4(), port));
                }
            }
        } catch (Exception e) {
            ConsoleOutput.error("[FEHLER] Proxy-Liste aus DB: " + e.getMessage());
        }
        return proxies;
    }

    private static String readWorkerId(Document instance) {
        for (String key : new String[]{"assignedWorkerId", "workerId", "rootserverId"}) {
            Object v = instance.get(key);
            if (v != null) return String.valueOf(v);
        }
        return null;
    }

    private static String readValue(MongoDbDatabaseManager db, String dbKey, String envKey) throws Exception {
        String env = System.getenv(envKey);
        if (env != null && !env.isBlank()) return env;
        return db.getConfigValue(dbKey);
    }

    private static int readIntValue(MongoDbDatabaseManager db, String dbKey, String envKey, int defaultValue)
            throws Exception {
        String value = readValue(db, dbKey, envKey);
        if (value == null || value.isBlank()) return defaultValue;
        try {
            return Integer.parseInt(value.trim());
        } catch (NumberFormatException e) {
            return defaultValue;
        }
    }

    private static void printBanner() {
        ConsoleOutput.info("");
        ConsoleOutput.info("╔══════════════════════════════════════╗");
        ConsoleOutput.info("║      CloudNetwork ProxyGateway       ║");
        ConsoleOutput.info("║  Minecraft Client → Velocity Proxy   ║");
        ConsoleOutput.info("╚══════════════════════════════════════╝");
        ConsoleOutput.info("");
    }
}
